/***********************************************************************/
/*                                                                     */
/*  FILE        :fvector.c                                             */
/*  DATE        :Fri, Apr 13, 2007                                     */
/*  DESCRIPTION :define the fixed vector table.                        */
/*  CPU GROUP   :26A                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.8).     */
/*                                                                     */
/***********************************************************************/

/*********************************************************************
 *  STARTUP for M16C/60,30,20,10
 *  Copyright(c) 2004 Renesas Technology Corp.
 *  And Renesas Solutions Corp.,All Rights Reserved.
 *  resetprg.c : startup file
 *
 *  Function:initialize each function
 *
 *
 * $Date: 2006/09/14 02:04:30 $
 * $Revision: 1.11 $
 *********************************************************************/

#pragma sectaddress     fvector,ROMDATA 0xfffdc


#pragma interrupt/v _dummy_int  //udi
#pragma interrupt/v _dummy_int  //over_flow
#pragma interrupt/v _dummy_int  //brki
#pragma interrupt/v _dummy_int  //address_match
#pragma interrupt/v _dummy_int  //single_step
#pragma interrupt/v _dummy_int  //wdt
#pragma interrupt/v _dummy_int  //dbc
#pragma interrupt/v _dummy_int  //nmi
#pragma interrupt/v start

_asm("    .id    ""\"#FFFFFFFFFFFFFF\"");

#pragma interrupt _dummy_int()
void _dummy_int(void){}

