/***********************************************************************/
/*                                                                     */
/*  FILE        :initsct.c                                             */
/*  DATE        :Fri, Apr 13, 2007                                     */
/*  DESCRIPTION :initialize each sections.                             */
/*  CPU GROUP   :26A                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.8).     */
/*                                                                     */
/***********************************************************************/

/***********************************************************
 *  STARTUP for M16C/60,30,20,10
 *  Copyright(c) 2004 Renesas Technology Corp.
 *  And Renesas Solutions Corp.,All Rights Reserved.
 *
 *  initsct.c : initialize each sections

 *
 * $Date: 2007/01/31 03:11:35 $
 * $Revision: 1.10.4.1 $
 ***********************************************************/
#include "initsct.h"
void initsct(void);

void initsct(void)
{
    sclear("bss_SE","data","align");
    sclear("bss_SO","data","noalign");
    sclear("bss_NE","data","align");
    sclear("bss_NO","data","noalign");
    sclear_f("bss_FE","data","align");
    sclear_f("bss_FO","data","noalign");
    // add new sections
    // bss_clear("new section name");

    scopy("data_SE","data","align");
    scopy("data_SO","data","noalign");
    scopy("data_NE","data","align");
    scopy("data_NO","data","noalign");
    scopy_f("data_FE","data","align");
    scopy_f("data_FO","data","noalign");
}
