/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "LedBar.h"
#include <stdint.h>
#include "MockLed.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_LedBar_0_percent_all_off(void);
extern void test_LedBar_100_percent_all_on(void);
extern void test_LedBar_19_percent_all_off(void);
extern void test_LedBar_20_percent_one_on(void);
extern void test_LedBar_50_percent_two_on(void);
extern void test_LedBar_99_percent_four_on(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  MockLed_Init();
}
static void CMock_Verify(void)
{
  MockLed_Verify();
}
static void CMock_Destroy(void)
{
  MockLed_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("TestLedBar.c");
  run_test(test_LedBar_0_percent_all_off, "test_LedBar_0_percent_all_off", 16);
  run_test(test_LedBar_100_percent_all_on, "test_LedBar_100_percent_all_on", 27);
  run_test(test_LedBar_19_percent_all_off, "test_LedBar_19_percent_all_off", 38);
  run_test(test_LedBar_20_percent_one_on, "test_LedBar_20_percent_one_on", 49);
  run_test(test_LedBar_50_percent_two_on, "test_LedBar_50_percent_two_on", 60);
  run_test(test_LedBar_99_percent_four_on, "test_LedBar_99_percent_four_on", 71);

  CMock_Guts_MemFreeFinal();
  return UnityEnd();
}
