# test-script for QUTest unit testing harness
# see https://www.state-machine.com/qtools/qutest.html

import sys
import pytest
import struct
from qspypy.qspy import FILTER, QS_OBJ_KIND


def on_reset(qutest):
    qutest.glb_filter(FILTER.SM)
    qutest.current_obj(QS_OBJ_KIND.SM,"the_msm")


def test_QMsmTst_init(qutest):
    qutest.init()
    qutest.expect("===RTC===> St-Init  Obj=the_msm,State=NULL->QMsmTst_s2")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s2")
    qutest.expect("===RTC===> St-Init  Obj=the_msm,State=QMsmTst_s2->QMsmTst_s211")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s21")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("%timestamp Init===> Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

def test_QMsmTst_dispatch(qutest_noreset):
    qutest = qutest_noreset # name change

    qutest.dispatch("A_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=A_SIG,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s21")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s21")
    qutest.expect("===RTC===> St-Init  Obj=the_msm,State=QMsmTst_s21->QMsmTst_s211")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=A_SIG,State=QMsmTst_s21->QMsmTst_s211")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("B_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=B_SIG,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=B_SIG,State=QMsmTst_s21->QMsmTst_s211")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("D_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=D_SIG,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Init  Obj=the_msm,State=QMsmTst_s21->QMsmTst_s211")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=D_SIG,State=QMsmTst_s211->QMsmTst_s211")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("E_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=E_SIG,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s21")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s2")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=E_SIG,State=QMsmTst_s->QMsmTst_s11")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("I_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=I_SIG,State=QMsmTst_s11")
    qutest.expect("%timestamp =>Intern Obj=the_msm,Sig=I_SIG,State=QMsmTst_s1")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("F_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=F_SIG,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s2")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s21")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=F_SIG,State=QMsmTst_s1->QMsmTst_s211")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("I_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=I_SIG,State=QMsmTst_s211")
    qutest.expect("%timestamp =>Intern Obj=the_msm,Sig=I_SIG,State=QMsmTst_s2")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("I_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=I_SIG,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Unhnd Obj=the_msm,Sig=I_SIG,State=QMsmTst_s2")
    qutest.expect("%timestamp =>Intern Obj=the_msm,Sig=I_SIG,State=QMsmTst_s")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("F_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=F_SIG,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s21")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s2")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=F_SIG,State=QMsmTst_s2->QMsmTst_s11")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("A_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=A_SIG,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Init  Obj=the_msm,State=QMsmTst_s1->QMsmTst_s11")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=A_SIG,State=QMsmTst_s1->QMsmTst_s11")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("B_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=B_SIG,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=B_SIG,State=QMsmTst_s1->QMsmTst_s11")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("D_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=D_SIG,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Unhnd Obj=the_msm,Sig=D_SIG,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Init  Obj=the_msm,State=QMsmTst_s->QMsmTst_s11")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=D_SIG,State=QMsmTst_s1->QMsmTst_s11")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("D_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=D_SIG,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Init  Obj=the_msm,State=QMsmTst_s1->QMsmTst_s11")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=D_SIG,State=QMsmTst_s11->QMsmTst_s11")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("E_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=E_SIG,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=E_SIG,State=QMsmTst_s->QMsmTst_s11")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("G_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=G_SIG,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s2")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s21")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=G_SIG,State=QMsmTst_s11->QMsmTst_s211")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("H_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=H_SIG,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s21")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s2")
    qutest.expect("===RTC===> St-Init  Obj=the_msm,State=QMsmTst_s->QMsmTst_s11")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=H_SIG,State=QMsmTst_s211->QMsmTst_s11")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("H_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=H_SIG,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Init  Obj=the_msm,State=QMsmTst_s->QMsmTst_s11")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=H_SIG,State=QMsmTst_s11->QMsmTst_s11")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("C_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=C_SIG,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s2")
    qutest.expect("===RTC===> St-Init  Obj=the_msm,State=QMsmTst_s2->QMsmTst_s211")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s21")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=C_SIG,State=QMsmTst_s1->QMsmTst_s211")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("G_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=G_SIG,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s21")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s2")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Init  Obj=the_msm,State=QMsmTst_s1->QMsmTst_s11")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=G_SIG,State=QMsmTst_s21->QMsmTst_s11")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("C_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=C_SIG,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s2")
    qutest.expect("===RTC===> St-Init  Obj=the_msm,State=QMsmTst_s2->QMsmTst_s211")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s21")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=C_SIG,State=QMsmTst_s1->QMsmTst_s211")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")

    qutest.dispatch("C_SIG")
    qutest.expect("%timestamp Disp===> Obj=the_msm,Sig=C_SIG,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s211")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s21")
    qutest.expect("===RTC===> St-Exit  Obj=the_msm,State=QMsmTst_s2")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s1")
    qutest.expect("===RTC===> St-Init  Obj=the_msm,State=QMsmTst_s1->QMsmTst_s11")
    qutest.expect("===RTC===> St-Entry Obj=the_msm,State=QMsmTst_s11")
    qutest.expect("%timestamp ===>Tran Obj=the_msm,Sig=C_SIG,State=QMsmTst_s2->QMsmTst_s11")
    qutest.expect("%timestamp Trg-Done QS_RX_EVENT")



if __name__ == "__main__":
    options = ['-x', '-v', '--tb=short']
    options.extend(sys.argv)
    pytest.main(options)
