#ifndef GUI_H
#define GUI_H

#include <QDialog>
#include "ui_gui.h" // generated by QtDesigner

class Gui : public QDialog, public Ui_Gui {
    Q_OBJECT

public:
    explicit Gui(QWidget *parent = 0);
    static Gui *instance;

private slots:
    void onBtnPressed();
    void onBtnReleased();
    void onQuit();

protected:
    virtual void wheelEvent(QWheelEvent *e);
    //virtual void keyPressEvent(QKeyEvent *e);
};

#endif // GUI_H
