/***********************************************************************/
/*                                                                     */
/*  FILE        :firm.c                                                */
/*  DATE        :Fri, Apr 13, 2007                                     */
/*  DESCRIPTION :set the firm area of OnChipDebuggers.                 */
/*  CPU GROUP   :26A                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.8).     */
/*                                                                     */
/***********************************************************************/

/*********************************************************
 *  STARTUP for M16C/60,30,20,10
 *  Copyright(c) 2004 Renesas Technology Corp.
 *  And Renesas Solutions Corp.,All Rights Reserved.
 *
 *
 *  firm.c
 *  When use FoUSB or E8,must be included
 *
 * $Date: 2005/11/01 05:32:33 $
 * $Revision: 1.8 $
 *********************************************************/
#include "typedefine.h"

#ifdef __E8__    // for E8

#pragma section bss FirmArea
_far _UBYTE _firmarea[0x800];    // dummy for monitor


#else    // for FoUSB

#pragma section bss FirmArea
_far  _UBYTE _firmarea[0x600];    // dummy for monitor
#endif





