/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "MockSpi.h"

static const char* CMockString_SPI_beginTransaction = "SPI_beginTransaction";
static const char* CMockString_SPI_endTransaction = "SPI_endTransaction";
static const char* CMockString_SPI_transfer = "SPI_transfer";
static const char* CMockString_data = "data";

typedef struct _CMOCK_SPI_beginTransaction_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_SPI_beginTransaction_CALL_INSTANCE;

typedef struct _CMOCK_SPI_transfer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_data;

} CMOCK_SPI_transfer_CALL_INSTANCE;

typedef struct _CMOCK_SPI_endTransaction_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_SPI_endTransaction_CALL_INSTANCE;

static struct MockSpiInstance
{
  CMOCK_MEM_INDEX_TYPE SPI_beginTransaction_CallInstance;
  CMOCK_MEM_INDEX_TYPE SPI_transfer_CallInstance;
  CMOCK_MEM_INDEX_TYPE SPI_endTransaction_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockSpi_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.SPI_beginTransaction_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SPI_beginTransaction);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SPI_transfer_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SPI_transfer);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SPI_endTransaction_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SPI_endTransaction);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void MockSpi_Init(void)
{
  MockSpi_Destroy();
}

void MockSpi_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void SPI_beginTransaction(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SPI_beginTransaction_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SPI_beginTransaction);
  cmock_call_instance = (CMOCK_SPI_beginTransaction_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SPI_beginTransaction_CallInstance);
  Mock.SPI_beginTransaction_CallInstance = CMock_Guts_MemNext(Mock.SPI_beginTransaction_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void SPI_beginTransaction_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SPI_beginTransaction_CALL_INSTANCE));
  CMOCK_SPI_beginTransaction_CALL_INSTANCE* cmock_call_instance = (CMOCK_SPI_beginTransaction_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SPI_beginTransaction_CallInstance = CMock_Guts_MemChain(Mock.SPI_beginTransaction_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void SPI_transfer(uint32_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SPI_transfer_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SPI_transfer);
  cmock_call_instance = (CMOCK_SPI_transfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SPI_transfer_CallInstance);
  Mock.SPI_transfer_CallInstance = CMock_Guts_MemNext(Mock.SPI_transfer_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_SPI_transfer,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SPI_transfer(CMOCK_SPI_transfer_CALL_INSTANCE* cmock_call_instance, uint32_t data);
void CMockExpectParameters_SPI_transfer(CMOCK_SPI_transfer_CALL_INSTANCE* cmock_call_instance, uint32_t data)
{
  cmock_call_instance->Expected_data = data;
}

void SPI_transfer_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SPI_transfer_CALL_INSTANCE));
  CMOCK_SPI_transfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_SPI_transfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SPI_transfer_CallInstance = CMock_Guts_MemChain(Mock.SPI_transfer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SPI_transfer(cmock_call_instance, data);
}

void SPI_endTransaction(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SPI_endTransaction_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SPI_endTransaction);
  cmock_call_instance = (CMOCK_SPI_endTransaction_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SPI_endTransaction_CallInstance);
  Mock.SPI_endTransaction_CallInstance = CMock_Guts_MemNext(Mock.SPI_endTransaction_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void SPI_endTransaction_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SPI_endTransaction_CALL_INSTANCE));
  CMOCK_SPI_endTransaction_CALL_INSTANCE* cmock_call_instance = (CMOCK_SPI_endTransaction_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SPI_endTransaction_CallInstance = CMock_Guts_MemChain(Mock.SPI_endTransaction_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

